# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Build documentation in the docs/api directory with Sphinx
sphinx:
  builder: html
  configuration: docs/api/conf.py
  # TODO: investigate warnings
  fail_on_warning: false

# Build docs in additional formats such as PDF and ePub
formats: all

# Specify dependencies to enable reproducible builds:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
     # TODO: no RTD scripts supported
     - requirements: requirements_pip.txt
     - method: pip
       path: .
