language: python
python:
- 3.6
- 3.7
- 3.8
- pypy3
env:
- INSTALL_VARIANT=pip
jobs:
  include:
  allow_failures:
  - python: pypy3
cache:
- pip
addons:
  apt:
    packages:
    - arping
branches:
  except:
  - master-experimental
  - tp-i2n
os: linux
dist: xenial
install:
- pip install -r requirements_pip.txt
# Clone-install Avocado
- VERSION=$(cat VERSION)
- git clone --depth 1 https://github.com/avocado-framework/aexpect.git aexpect-libs
- cd aexpect-libs
- pip install -e .
- cd ..
- git clone --depth 1 --branch $VERSION https://github.com/avocado-framework/avocado.git avocado-libs
- cd avocado-libs
- pip install -e .
- cd ..
# Clone-install Avocado-vt
- git clone --depth 1 --branch $VERSION https://github.com/avocado-framework/avocado-vt.git avocado-vt-libs
- cd avocado-vt-libs
- pip install -e .
- cd ..
- pip install -e .
before_script:
- sleep 3
# TODO: python3.8 adds phantom lines reducing the coverage so update to a fixed version
- if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then pip install coverage==5.0; fi
script:
- make check
# Running will take too much time building the required vms but we can at least validate noop runs and the list of tests
- avocado vt-bootstrap --vt-skip-verify-download-assets --yes-to-all
- coverage run --append --source=avocado_i2n $(which avocado) manu setup=noop
- coverage run --append --source=avocado_i2n $(which avocado) list --loaders cartesian_graph -- "only=tutorial1"
- coverage run --append --source=avocado_i2n $(which avocado) run --auto --loaders cartesian_graph -- "only=tutorial1 dry_run=yes"
# Collect all coverage
- coverage report -m
- codecov
# Cleanup avocado(-vt) libs
- rm -rf avocado-vt-libs
- rm -rf avocado-libs
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: ALzPshHJvQ0ouM74gntpgDBYp0YcbxGjVkGvTGmbPBzQ/ImiuFDbLP/bq8CW50/hZBoGW7qB0wrttiKQ5jXHRE/hljcL66DeYDBq+ONaTIRy8l6gcoUXN7JmELxuojO6gKzMV1Zixhzbmvz7gFNvOsLpjDOqER0bOzwkxvNilI8VN0ObIN7zVzv/Fkahx0yWQjjM48Xxs4V1p3Q4MAeMpKr1SbbHXRlB2F7/lFmkmYVX9TomnhVigu8qt1yKmCORDhHq7uFj9BLdlqCs4fX+fAoQQbLdRg4+/wT1o2tjSXH+f7rzZU4bgFnFB25PS+Ycb/7TbhRcsRzdo0JDj2AGIRpg+CH/GivJwvLoLlPNh3/d5ZFB0kNNVI6T9jnEQY1HqpCldwuBLJc7aBppAUxXc0UF/UXFjRYpUsQkSxC+Rqj6Zoz3z0JCSYEKGu7dfFIGh8QYnrkabedAz8jRODnCE5t/Nc0CrNuRGilS2K5mU3cLaXqWQWCjONZh8HQwByusp/nRtuX2zgBQlcUTM2SXqixlhSrxRlLYvwOS383/RMCwUqaY/DIzmI+CMhLzumv2Tk0SArdUgueqiq0y1Xasb+0FZONnpZkzCOd9pgDiSTF7wR42rNTMLokoZFuMT5DAguX3NnhHuYCqWoaBYl5oS6qnjSHx375DeNVrtbHBB88=
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    tags: true
