#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# avocado-i2n documentation build configuration file, created by
# sphinx-quickstart on Tue Feb 12 18:27:14 2019.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
# -> uncommented and currently used (../.. instead of .):
import os
import sys
sys.path.insert(0, os.path.abspath('../..'))

# Add mock modules to integrate better with platforms like ReadTheDocs. Any
# modules that include C code will not be automatically imported in this online
# platform which is understandable for security reasons. So we have to replace
# them with mock modules in order for the build to succeed (we don't expect
# these to be used for the documentation build in normal circumstances anyway).
import mock
# TODO: no recent version of avocado-vt is available on PyPI so use this as a
# temporary workaround to provide the missing modules until either this or the
# prescript support of readthedocs.yml improves
MOCK_MODULES = ['virttest', 'virttest.utils_params', 'virttest.cartesian_config',
                'avocado_vt', 'avocado_vt.test', 'avocado_vt.loader']
for mod_name in MOCK_MODULES:
    sys.modules[mod_name] = mock.Mock()
# TODO: this problem extends even further to classes
sys.modules['avocado_vt.test'].VirtTest = mock.Mock
sys.modules['avocado_vt.loader'].VirtTestLoader = mock.Mock

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.viewcode',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'source/modules'

# General information about the project.
project = 'avocado-i2n'
copyright = '2019, Intra2net AG'
author = 'Intra2net AG'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = ''
# The full version, including alpha/beta/rc tags.
release = ''

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'Python'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'default'  # was 'alabaster'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'avocado-i2ndoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'avocado-i2n.tex', 'avocado-i2n Documentation',
     'Intra2net AG', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'avocado-i2n', 'avocado-i2n Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'avocado-i2n', 'avocado-i2n Documentation',
     author, 'avocado-i2n', 'One line description of project.',
     'Miscellaneous'),
]


# -- Customization on methods to display ----------------------------------

# Show doc of class AND of constructor
autoclass_content = 'class'  # 'both' not needed if special-members is used
                             # as default flag
autodoc_default_flags = ['members', 'special-members', 'undoc-members',
                         'show-inheritance']

# Sort by source (instead of alphabetically)
autodoc_member_order = 'bysource'

# want to keep __init__ members but exclude other special members
def skip_class_members(app, what, name, obj, skip, options):
    if skip:
        # do skip
        return True
    if what not in ('class', 'exception'):
        # following rules only apply to class members
        return False
    if name in ('__weakref__', '__dict__', '__module__', '__doc__'):
        # always skip these since they are usually not present in source code
        return True
    # skip getters and setters for the sake of properties
    if name.startswith("get_") or name.startswith("set_"):
        return True
    return False

def setup(app):
    # custom setup to include constructors to be documented
    app.connect('autodoc-skip-member', skip_class_members)
    # import main package here to be able to import all sphinx-apidoc imported modules
    import avocado_i2n
