name: Lint Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy types-setuptools black pycodestyle pydocstyle

      - name: Run linters
        run: |
          mypy avocado_i2n
          black --check --diff --color avocado_i2n
          # only excluded checks are conflicts with black and within pycodestyle
          # (in addition E402 is not something we intend to follow)
          pycodestyle --ignore=E203,E402,E501,W503 avocado_i2n
          pydocstyle avocado_i2n
